[package]
name = "uofu-cs-discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.5.6"
tokio = { version = "1.33.0", features = ["rt", "macros", "rt-multi-thread"] }
rand = "0.8.5"
chrono = "0.4.31"
serde = "1.0.189"
toml = "0.8.2"
regex = "1.10.2"
anyhow = "1.0.75"
dashmap = "5.5.3"
nom = "7.1.3"
emojis = "0.6.1"
notify = "6.1.1"
